data:
  batch_size: 32
  flatten: true
  normalize: false
  train_split: 0.7
  val_split: 0.15
  random_seed: 42
  groups: [HC, MCI, AD]

filter:
  type: BandPassFilter
  tr: 3
  flp: 0.01
  fhi: 0.08
  k: 2
  remove_artifacts: true
  apply_demean: true
  apply_detrend: true
  apply_finalDetrend: false
