data:
  batch_size: 64
  groups: [HC, MCI, AD]
  random_seed: 42
  train_split: 0.7
  val_split: 0.15
  datasplit_file: data/train_val_test_split.csv
  datasplit_mode: load
  normalize: true
  transpose: false
  pad_features: true
  truncate_features: false
  flatten: false
  timepoints_as_samples: false
  fc_input: false

filter:
  apply_demean: true
  apply_detrend: true
  apply_finalDetrend: false
  fhi: 0.08
  flp: 0.01
  k: 2
  remove_artifacts: true
  tr: 3000
  type: BandPassFilter
